deepseek:
  api_key: sk-599d81d5ebf5469eaca1d9de8c89170a
  model: deepseek-chat
  max_tokens: 4096
  temperature: 1.5

openai:
  api_key:
  model: gpt-3.5-turbo
  max_tokens: 4096
  temperature: 1.5


anthropic:
    api_key:
    model: claude-3-7-sonnet-20250219
    max_tokens: 4096
    temperature: 1.5

email: zyx2015441509@gmail.com